# Generated by Django 5.0.6 on 2024-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=253)),
                ('image', models.ImageField(upload_to='img')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
